### ISSUE TITLE
[Feature Request] Easter Customs / Traditions

### ISSUE THREAD

**Issue by jodth07** [python-discord/seasonalbot#157]
We would all love to know what it's like on the other side, and for this season, we would like to know how the other sides celebrate Easter. Each country, territory, group, may have their own way of celebrating Easter, and to that end, we are going to create a bot command that will provide such information. 

When called, the bot command will provide one random easter tradition/custom found in a particular location in the world.

## Implementation details

List the changes required for the implementation here.

- [ ] Write the bot command `easter_tradition`
- [ ] provide random tradition or custom of a country or territory 

## Happy Early Easter !

**Comment by JulieGumerman** [comment]
So, I have never contributed to an open source project, but I am interested in participating in this one. What can I do to help? I'm newish to coding.

**Comment by scragly** [comment]
@JulieGumerman if you're in the Python Discord server, pop into the `#seasonalbot-chat` channel and we'll help give you an introduction to the project and guide you in getting started. 

If you're not part of our discord community yet, you'll have to join us over there first in order to participate, [so come on over](https://discord.gg/python), we'll be happy to have you :)

**Comment by RohanRadia** [comment]
I can handle this. Thanks.

**Comment by SebastiaanZ** [comment]
This was merged with #181
