### ISSUE TITLE
Wikify Seasonalbot's README

### ISSUE THREAD

**Issue by sco1** [python-discord/seasonalbot#220]
[Seasonalbot's README](https://github.com/python-discord/seasonalbot/blob/master/README.md) is a bit dense, and will only get moreso as we add guidance on getting the database up and running for local dev along with any other editor-specific guidance we work on adding.

This will be a great addition to our upcoming Django-wiki, but this can live in this project's GH wiki for now since both will accept markdown.

The README has been copy/pasted into the GH wiki: https://github.com/python-discord/seasonalbot/wiki

A couple TODOs that I can think of right now:

- [x] Rework the PyCharm specific guide to utilize the separate pages for generic tasks
- [ ] Add guides for other editors (e.g. VSCode)
- [x] Add a generic "getting started" page that outlines the general flow for getting set up to run the bot & contribute code to the project
- [x] Rework formatting & add some more to the pages where appropriate
- [ ] Add sidebar/footer
- [x] Rework the repo's README.md & point the specifics to the wiki
- [ ] Add steps for getting the bot running w/Docker

**Comment by MarkKoz** [comment]
I'm working creating a general "getting started" page. I've ran into [this](https://github.com/python-discord/seasonalbot/wiki/Getting-Started-With-PyCharm#working-with-git) section which bugs me:

> Each pull request you work on should have its own branch. This keeps your master branch clean so you can pull changes from the original repository without pulling the same commits you’ve already added to your fork.

This is a confusing explanation. It legitimately took me a few minutes to make sense of it. And once I understood, I knew I could just do `git pull upstream master` and it wouldn't even matter what `origin/master` has anyway.

Can someone think of a better explanation for this?

**Comment by MarkKoz** [comment]
Should we link to [GitHub's guide](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) instead for creating a PR? It actually nicely done. However, we may need to emphasise that `Allow edits from maintainers` must remain checked.

**Comment by lemonsaurus** [comment]
@MarkKoz you asked a lot of questions, here's a lot of answers.

# Git
* `git diff` and `git log` are probably worth mentioning. Perhaps we could just link to an article about "other useful git commands" and put it there?
* I like to use the argument that we create other branches on the fork so that we can work on multiple issues at the same time. If we don't, we would need to wait for one pull request to be merged in order to "free up" `master` so we could tackle the next one.
* there's some git best practice stuff in the contributing guidelines, and I guess I feel like that's enough, though it probably wouldn't hurt to reiterate some of those points.
* IMO the editor articles don't need to explain git concepts at all, they can just link articles that do.

# PyCharm
* Oh yes, using `-m` bugs me too. Please change it.
* `focus on purely describing how to do something` sounds like exactly the right idea.

# New pages
* In the long run, we are going to expose the linting problems to the GitHub, so that it will not be necessary for users to navigate to Azure DevOps at all. Still, a guide explaining about builds and what to do if they fail is probably a good idea. We could show off what a failing build looks like both on GH and in #seasonalbot-log, and then show some screenshots of how to find more information so you can get it to pass, maybe mention precommit again.
* A page about adding a dependency sounds useful. :+1: 
* A Python installation guide, in my opinion, falls outside the scope of this wiki. :-1: 

# Other
* That GitHub guide for creating a PR looks great. I wouldn't mind if we just used that, so long as we underline the importance of allowing edits from maintainers.
* I don't really understand how the Docker question is related to this wiki issue. Perhaps it'd be a discussion better suited for a different issue.

**Comment by MarkKoz** [comment]
> IMO the editor articles don't need to explain git concepts at all, they can just link articles that do.

I guess I contradicted myself by saying "focus purely on how to do something". The workflow covers the steps to take, but doesn't explain what anything is by itself (what is a branch? what is a commit? what is a push?). Considering that we are suggesting PyCharm as the beginner-friendly route, I think it is worthwhile to provide some explanation at least for PyCharm.

I like how I briefly explained things in the Git CLI guide. I'd like to follow a similar pattern for PyCharm but I was wondering if I could structure the wiki in a way that would allow me to avoid repeating the same content. Now I am leaning even more towards just letting it be repeated, as it's not too long anyway and the explanations are more effective when paired with the how-to's.

> I don't really understand how the Docker question is related to this wiki issue.

It was addressing ELA's suggestion: "Add steps for getting the bot running w/Docker"

**Comment by MarkKoz** [comment]
Might be worth adding how to create the `.env` file e.g. with `touch .env` or `type nul > .env` on Windows.

**Comment by sco1** [comment]
Sounds good, go for it

**Comment by MarkKoz** [comment]
I added the two I mentioned but it could also use a PowerShell one if someone wants to figure that out.

**Comment by sco1** [comment]
Closing this as its been superseded by https://pythondiscord.com/pages/contributing/seasonalbot/
