### ISSUE TITLE
Feature Request - suggest. to suggest something any potential change in the server.

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#330]
Its a basic command nothing more, just do `.suggest [a suggestion here]` which send a embed with a suggestion along two reaction (upvote, downvote) to choose whether people like it or not 
Optional :- add a command(permission = mods/admins) that take a URL of that suggestion message to reply to a suggestion if that's not possible or is useless. and remove the reactions to stop allowing anymore voting

## Implementation details

List the changes required for the implementation here.

- [ yes] Write the bot command
- [ yes] Add the command to our README.md
- Need a new channel.

**Comment by SebastiaanZ** [comment]
Suggestions to our resources list can be made as an issue on either our `meta` repository or, otherwise` our `site` repository. (It was traditionally the latter, since adding one required a PR to be merged, but now we've moved to a wiki-based resources page, maybe `meta` is a better place. I don't know.)

In any case, our resources list is highly curated and we aim to keep it as short as possible. This means that the format of a user opening an issue followed by an internal discussion is a better procedure than a bot function with a general vote, as we can then also discuss removing another item in favour of the suggested one.

That means I'm closing this issue.

**Comment by AG4lyf** [comment]
it have no relation to resources page. 
its for suggesting possible changes in the servers or bots . etc . for people who don't use or know github.

**Comment by SebastiaanZ** [comment]
Then I misunderstood your suggestion, but the answer does not really change.

Suggestions for our community can already be made over at the `meta` repository, where they can receive a proper discussion. We don't want to make decisions regarding the community based on simple upvote/downvote mechanisms and conversations between people living in vastly different timezones are much easier in the form of a GitHub Issue thread than a live chat thread where most of the potential participants are not present.

In the end, the most important aspect of using GitHub over a live chat is that the comments made on the issue say preserved. This helps in the short run when we need to take a decision on a suggestion internally (e.g., in a staff meeting) and in the long run when people want to read back what has been said on something in the past.
