### ISSUE TITLE
.apod command for Astronomy Picture of the Day.

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#357]
## Description
Basic Idea is to use NASA's public API to fetch Astronomy Picture of the Day. This contain a description and a picture with a title with respect to the topic that changes every 24 hours. 

## Reasoning
It looks cool similar to .games and .movies commands.

## Proposed Implementation
Use NASA's API and json to get a embed and send it . very easy
Also we will need a constant as nasa API's Auth key. 

## Additional Details
Here you can see how it looks like 
![image](https://user-images.githubusercontent.com/45149585/75168576-200c5980-574d-11ea-92dd-dd9393d58561.png)
![image](https://user-images.githubusercontent.com/45149585/75168799-7e393c80-574d-11ea-8eaa-9329ba197bd3.png)
![image](https://user-images.githubusercontent.com/45149585/75168815-82fdf080-574d-11ea-8e14-3750edab2569.png)
I think 3 of them are enough to get the idea of how it will look like

## Would you like to implement this yourself?

- [] I'd like to implement this feature myself

**Comment by sco1** [comment]
All of these (#357, #358, #359, #360) look fine. Rather than implementing these as individual cogs, they should ultimately end up being contained inside one cog and implemented as subcommands.

With that in mind, please take a look at their respective APIs and see if there is any functionality that could be implemented for each beyond just returning a random picture. Are there any "generes" or other filters that we could use? Photos from specific missions? Specific topic araeas? etc.

**Comment by AG4lyf** [comment]
so 
cog named space :
.apod
.nasa
.mars
.earth 
If i am not wrong.

**Comment by sco1** [comment]
That should be a fine start
