### ISSUE TITLE
.earth command to retrive random picture of earth.

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#359]
## Description
This is not as cool as the other 3 of the commands. but it looks nice. retrives earth picture taken by NASA's satellite . Implementation similar to #357 .

## Reasoning
It looks cool similar to .games and .movies commands.

## Proposed Implementation
Use NASA's API and json to get a embed and send it . very easy
Also we will need a constant as nasa API's Auth key.

## Additional Details
![image](https://user-images.githubusercontent.com/45149585/75169566-cad14780-574e-11ea-877a-618499e49990.png)
![image](https://user-images.githubusercontent.com/45149585/75169620-e0467180-574e-11ea-93b4-e29bab71347e.png)
![image](https://user-images.githubusercontent.com/45149585/75169632-e5a3bc00-574e-11ea-9299-d4fa72e7f322.png)

## Would you like to implement this yourself?

- []  I'd like to implement this feature mysel

**Comment by sco1** [comment]
All of these (#357, #358, #359, #360) look fine. Rather than implementing these as individual cogs, they should ultimately end up being contained inside one cog and implemented as subcommands.

With that in mind, please take a look at their respective APIs and see if there is any functionality that could be implemented for each beyond just returning a random picture. Are there any "generes" or other filters that we could use? Photos from specific missions? Specific topic araeas? etc.
