### ISSUE TITLE
.mars command to get pics by rovers on mars

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/seasonalbot#360]
## Description
Out of all the command using this API this is the best looking and feeling command.
It come with 1 downside . There is lack of pictures provided by NASA through there API.
Implementation similar to #357 

## Reasoning
It looks cool similar to .games and .movies commands.

## Proposed Implementation
Use NASA's API and json to get a embed and send it . very easy
Also we will need a constant as nasa API's Auth key.

## Additional Details

![image](https://user-images.githubusercontent.com/45149585/75170036-81cdc300-574f-11ea-8b5c-570b365e7fd3.png)
![image](https://user-images.githubusercontent.com/45149585/75170063-8eeab200-574f-11ea-9644-43a7d3d9a29a.png)
![image](https://user-images.githubusercontent.com/45149585/75170114-9f9b2800-574f-11ea-8223-d4ceb63dda65.png)

## Would you like to implement this yourself?
- [] I'd like to implement this feature myself

**Comment by sco1** [comment]
All of these (#357, #358, #359, #360) look fine. Rather than implementing these as individual cogs, they should ultimately end up being contained inside one cog and implemented as subcommands.

With that in mind, please take a look at their respective APIs and see if there is any functionality that could be implemented for each beyond just returning a random picture. Are there any "generes" or other filters that we could use? Photos from specific missions? Specific topic araeas? etc.

**Comment by AG4lyf** [comment]
@ks129 As you are the one who is currently working on this. 
I want to bring in your view that there is a huge lack of picture from NAVCAM and Rear CAM 
You should include pictures from inside cameras. otherwise it's quiet useless to see same 5-7 pictures

**Comment by ks129** [comment]
@AG4lyf Cameras is random in ny code, and my code support all 3 rovers. I think this will not affect it.
