### ISSUE TITLE
.snakes about has the wrong prefix

### ISSUE THREAD

**Issue by DuckMasterAl** [python-discord/seasonalbot#374]
## Description

The text in the `.snakes about` command has the wrong prefix for the commands you should try. It uses `!` as a prefix instead of `.`

## Steps to Reproduce

1. Do `.snakes about`
2. Read the embed and notice the bot's command has a prefix with `!` not `.`

## Expected Behaviour

It talks about the bot then says
The bot says
> Make sure you check out `.snakes sal`, `.snakes draw` and `.snakes hatch` to see what they came up with.
in the embed

## Actual Behaviour

The bot says
> Make sure you check out `!snakes sal`, `!snakes draw` and `!snakes hatch` to see what they came up with.
in the embed

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions

Change the text on the embed to change the command prefix from `!` to `.`

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by DuckMasterAl** [comment]
Improper Lines: https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/snakes/snakes_cog.py#L953-L954

Just change them to:
> "walked away as grand champions. Make sure you check out `.snakes sal`, `.snakes draw` "
> "and `.snakes hatch` to see what they came up with."

**Comment by kwzrd** [comment]
Good spot! Since you've ticked that you'd like to fix this, I'll assign you.

Statically referring to the prefix introduces a bit of a maintenance debt in the sense that should the prefix change in the future (or in a development environment), the help will be outdated again. At runtime, the prefix is available as a constant [here](https://github.com/python-discord/seasonalbot/blob/dc86d6714163f3d4006f71fcc7839dd6e24aa6ee/bot/constants.py#L67), so this could be made dynamic. This way, when overriding the prefix with an environment variable, the message will remain truthful. It's up to you whether you want to do this, but if we change it here, then I think it'd also be worth it to adjust other messages across the repo (I haven't checked how many there are).

**Comment by DuckMasterAl** [comment]
Hey,
Sorry I kind of didn't open Github and just was on Github Desktop for a while...
I've just changed the prefix to the one right now since I'm a little busy this week, anyone else can feel free to help and change it though!
Thanks,
DuckMasterAl

**Comment by kwzrd** [comment]
Sounds good, no worries.

Thanks for opening the PR, I will take a look tonight!

**Comment by DuckMasterAl** [comment]
I came back to this and added ctx.prefix to the pr.
