### ISSUE TITLE
Minesweeper issue

### ISSUE THREAD

**Issue by GalaxyCube101** [python-discord/seasonalbot#422]
## Description
Two issues, one: The top row of the XY board on iOS is broken, and two: I lost on my first move, which doesn’t happen in normal Minesweeper.

## Steps to Reproduce
Play Minesweeper on iOS

## Expected Behaviour
I expected normal letters on the top row and to not die on the first move.

## Actual Behaviour
The top row was bugged and I lost on my first move. 

## Known Impacted Platforms

- [ ] Web
- [ ] Desktop
- [ ] Android App
- [x] iOS App

## Possible Solutions
Use Unicode emojis from iOS devices, and change the loading behavior of the board to load after the first move. 

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

![C60A348A-EAA7-48B7-9DD1-E7BBE48598BC](https://user-images.githubusercontent.com/61128491/86065732-38ef8900-ba25-11ea-89e5-47722d24b888.jpeg)

**Comment by MarkKoz** [comment]
Unicode emoji are being used. It's a bug with the iOS app. Unicode flags are comprised of the regional indicators but the app doesn't realise displaying flags was not intended here. There seems to be no solution on our end. A workaround is to flip the top and side rows so that the letters are on the side.

> I lost on my first move, which doesn’t happen in normal Minesweeper.

I don't necessarily consider this a bug. This behaviour depends on the version of the game being played. It's not strictly required for all implementations to follow this behaviour. If someone wants to change it anyway, that's fine.

**Comment by vivax3794** [comment]
tbh I dont really like the code I wrote for minesweeper, so I would be up for just rewriting the hole cog.

**Comment by algo-1** [comment]
I’m willing to give this a go
